#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
source venv/bin/activate

export LM_PROSE_TARGET_TOKENS="${LM_PROSE_TARGET_TOKENS:-1000000000}"
export ENABLE_APP_DESC="${ENABLE_APP_DESC:-1}"
export ENABLE_WIKIPEDIA="${ENABLE_WIKIPEDIA:-1}"
export ENABLE_FINEWEB_EDU="${ENABLE_FINEWEB_EDU:-1}"
export ENABLE_MSMARCO_PASSAGES="${ENABLE_MSMARCO_PASSAGES:-1}"
export ENABLE_DOLLY_PROSE="${ENABLE_DOLLY_PROSE:-1}"

export APP_DESC_MAX_DOCS="${APP_DESC_MAX_DOCS:-100000}"
export WIKIPEDIA_MAX_DOCS="${WIKIPEDIA_MAX_DOCS:-0}"
export FINEWEB_EDU_MAX_DOCS="${FINEWEB_EDU_MAX_DOCS:-0}"
export MSMARCO_PASSAGE_MAX_DOCS="${MSMARCO_PASSAGE_MAX_DOCS:-300000}"
export DOLLY_PROSE_MAX_DOCS="${DOLLY_PROSE_MAX_DOCS:-0}"

scripts/prepare_lm_prose.sh --overwrite "$@"
